### ISSUE TITLE
Automated DXE-ectomy

### ISSUE THREAD

**Issue by rjoleary** [linuxboot/fiano#218]
This UTK visitor would automatically remove as many DXEs as possible while still ensuring the Firmware Image boots according to some test. The command line syntax would resemble:

```
utk image.bios \
    dxeectomy test_script.sh \
    save dxeectomy_image.bios
```

The list of DXEs removed will be printed. The `test_script.sh` is passed a path to a firmware image as the first argument. It is assumed this script will reflash and boot the BIOS, returning 1 if the test failed.

The algorithm would be something like:

```
D = set of DXEs
R = {}

def DXEectomyRound():
    for d in D:
        if test(D - (R U {d})) passes:
            R = R U {d}

def DXEectomy():
    repeat:
        DXEectomyRound()
        break if R has changed
    return R
```

**Comment by GanShun** [comment]
We might want to extend this so that the dxectomy can do a pe32 replacement. 

If we can replace ip stacks and disk drivers with linuxboot, we don't need those dxes, but if there's no way to replace_pe32 during the dxeectomy, the tests may fail.

If linux fits without removing any dxes, this is pretty simple, but what if it doesn't? we often want to do this so that we can gain space, so the operation might need to try to remove a set of dxes first to be able to fit linuxboot in.

**Comment by rjoleary** [comment]
Done in #223
